const Database = require('better-sqlite3');
const path = require('path');
const db = new Database(path.join(process.cwd(), 'prisma', 'dev.db'));

const tables = [
  `CREATE TABLE IF NOT EXISTS Parametres (id INTEGER PRIMARY KEY, nomBriqueterie TEXT DEFAULT '', telephone TEXT DEFAULT '', adresse TEXT DEFAULT '', devise TEXT DEFAULT 'FCFA', tarifParSac REAL DEFAULT 0, conditionPaiement TEXT DEFAULT 'Paiement sous 14 jours', logo TEXT DEFAULT '')`,
  `CREATE TABLE IF NOT EXISTS Brique (id INTEGER PRIMARY KEY AUTOINCREMENT, nom TEXT NOT NULL, dimensions TEXT NOT NULL, prixVente REAL NOT NULL, stockActuel INTEGER DEFAULT 0, stockMin INTEGER DEFAULT 0, createdAt DATETIME DEFAULT CURRENT_TIMESTAMP)`,
  `CREATE TABLE IF NOT EXISTS Client (id INTEGER PRIMARY KEY AUTOINCREMENT, nom TEXT NOT NULL, telephone TEXT DEFAULT '', adresse TEXT DEFAULT '', createdAt DATETIME DEFAULT CURRENT_TIMESTAMP)`,
  `CREATE TABLE IF NOT EXISTS Devis (id INTEGER PRIMARY KEY AUTOINCREMENT, numero TEXT UNIQUE NOT NULL, clientId INTEGER NOT NULL, dateEmission DATETIME DEFAULT CURRENT_TIMESTAMP, dateValidite DATETIME NOT NULL, transport REAL DEFAULT 0, notes TEXT DEFAULT '', statut TEXT DEFAULT 'en_attente', createdAt DATETIME DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(clientId) REFERENCES Client(id))`,
  `CREATE TABLE IF NOT EXISTS LigneDevis (id INTEGER PRIMARY KEY AUTOINCREMENT, devisId INTEGER NOT NULL, briqueId INTEGER NOT NULL, quantite INTEGER NOT NULL, prixUnit REAL NOT NULL, FOREIGN KEY(devisId) REFERENCES Devis(id) ON DELETE CASCADE, FOREIGN KEY(briqueId) REFERENCES Brique(id))`,
  `CREATE TABLE IF NOT EXISTS Commande (id INTEGER PRIMARY KEY AUTOINCREMENT, numero TEXT UNIQUE NOT NULL, clientId INTEGER NOT NULL, devisId INTEGER UNIQUE, dateCommande DATETIME DEFAULT CURRENT_TIMESTAMP, dateLivraisonPrevue DATETIME, acompte REAL DEFAULT 0, transport REAL DEFAULT 0, notes TEXT DEFAULT '', statut TEXT DEFAULT 'en_attente', createdAt DATETIME DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(clientId) REFERENCES Client(id), FOREIGN KEY(devisId) REFERENCES Devis(id))`,
  `CREATE TABLE IF NOT EXISTS LigneCommande (id INTEGER PRIMARY KEY AUTOINCREMENT, commandeId INTEGER NOT NULL, briqueId INTEGER NOT NULL, quantite INTEGER NOT NULL, prixUnit REAL NOT NULL, FOREIGN KEY(commandeId) REFERENCES Commande(id) ON DELETE CASCADE, FOREIGN KEY(briqueId) REFERENCES Brique(id))`,
  `CREATE TABLE IF NOT EXISTS Livraison (id INTEGER PRIMARY KEY AUTOINCREMENT, numero TEXT UNIQUE NOT NULL, commandeId INTEGER UNIQUE NOT NULL, dateLivraison DATETIME DEFAULT CURRENT_TIMESTAMP, livreur TEXT DEFAULT '', notes TEXT DEFAULT '', statut TEXT DEFAULT 'livree', createdAt DATETIME DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(commandeId) REFERENCES Commande(id))`,
  `CREATE TABLE IF NOT EXISTS LigneLivraison (id INTEGER PRIMARY KEY AUTOINCREMENT, livraisonId INTEGER NOT NULL, briqueId INTEGER NOT NULL, quantiteCommandee INTEGER NOT NULL, quantiteLivree INTEGER NOT NULL, FOREIGN KEY(livraisonId) REFERENCES Livraison(id) ON DELETE CASCADE, FOREIGN KEY(briqueId) REFERENCES Brique(id))`,
  `CREATE TABLE IF NOT EXISTS Facture (id INTEGER PRIMARY KEY AUTOINCREMENT, numero TEXT UNIQUE NOT NULL, livraisonId INTEGER UNIQUE NOT NULL, dateEmission DATETIME DEFAULT CURRENT_TIMESTAMP, dateEcheance DATETIME NOT NULL, transport REAL DEFAULT 0, notes TEXT DEFAULT '', statut TEXT DEFAULT 'impayee', createdAt DATETIME DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(livraisonId) REFERENCES Livraison(id))`,
  `CREATE TABLE IF NOT EXISTS Paiement (id INTEGER PRIMARY KEY AUTOINCREMENT, factureId INTEGER NOT NULL, montant REAL NOT NULL, date DATETIME DEFAULT CURRENT_TIMESTAMP, notes TEXT DEFAULT '', FOREIGN KEY(factureId) REFERENCES Facture(id) ON DELETE CASCADE)`,
  `CREATE TABLE IF NOT EXISTS SortieStock (id INTEGER PRIMARY KEY AUTOINCREMENT, briqueId INTEGER NOT NULL, quantite INTEGER NOT NULL, type TEXT NOT NULL, notes TEXT DEFAULT '', date DATETIME DEFAULT CURRENT_TIMESTAMP, createdAt DATETIME DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(briqueId) REFERENCES Brique(id))`,
  `CREATE TABLE IF NOT EXISTS ProductionJour (id INTEGER PRIMARY KEY AUTOINCREMENT, date DATETIME DEFAULT CURRENT_TIMESTAMP, totalSacs INTEGER NOT NULL, montantDu REAL NOT NULL, montantVerse REAL DEFAULT 0, statut TEXT DEFAULT 'impaye', notes TEXT DEFAULT '', createdAt DATETIME DEFAULT CURRENT_TIMESTAMP)`,
  `CREATE TABLE IF NOT EXISTS ProductionJourBrique (id INTEGER PRIMARY KEY AUTOINCREMENT, productionJourId INTEGER NOT NULL, briqueId INTEGER NOT NULL, nombreSacs INTEGER NOT NULL, FOREIGN KEY(productionJourId) REFERENCES ProductionJour(id) ON DELETE CASCADE, FOREIGN KEY(briqueId) REFERENCES Brique(id))`,
];

tables.forEach(sql => db.prepare(sql).run());
console.log('Base de données créée avec succès !');
db.close();
